version: '2.4'

services:
  ccd-message-publisher:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmcts/ccd-message-publisher
    container_name: ccd-message-publisher
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATA_STORE_DB_HOST: ccd-shared-database
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME: "${DB_USERNAME}"
      DATA_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      # For debug
      # JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - $SERVER_PORT:$SERVER_PORT
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true
