# TODO: Use env vars in all places where appropriate, with sensible defaults
server:
  port: 4455

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: ccd-message-publisher
  main:
    allow-bean-definition-overriding: true
  jms:
    servicebus: 
      connection-string: 
      idle-timeout: 1800000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5050/ccd_data?stringtype=unspecified
    username: ccd
    password: ccd
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      maxLifetime: 7200000
      connectionTimeout: 30000
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration

message-publisher:
  tasks[0]:
    message-type: CASE_EVENT
    destination: ccd-case-events-demo
    schedule: "*/10 * * * * *"
    batch-size: 1000
    enabled: true

